# Generated by Django 4.2.7 on 2025-09-17 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version identifier for the data', max_length=50, unique=True)),
                ('total_companies', models.PositiveIntegerField(default=0, help_text='Total number of companies in the database')),
                ('carbon_neutral_count', models.PositiveIntegerField(default=0, help_text='Number of carbon neutral companies')),
                ('renewable_data_count', models.PositiveIntegerField(default=0, help_text='Number of companies with renewable energy data')),
                ('public_companies_count', models.PositiveIntegerField(default=0, help_text='Number of public companies')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this version was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Version',
                'verbose_name_plural': 'Data Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Primary domain of the company (e.g., google.com)', max_length=255, unique=True)),
                ('company', models.CharField(db_index=True, help_text='Company name', max_length=255)),
                ('carbon_neutral', models.BooleanField(default=False, help_text='Whether the company is carbon neutral')),
                ('renewable_share_percent', models.FloatField(blank=True, help_text='Percentage of renewable energy usage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('parent', models.CharField(blank=True, help_text='Parent company name', max_length=255, null=True)),
                ('headquarters', models.CharField(blank=True, help_text='Company headquarters location', max_length=255, null=True)),
                ('sector', models.CharField(blank=True, help_text='Business sector/industry', max_length=100, null=True)),
                ('esg_policy', models.TextField(blank=True, help_text='Environmental, Social, and Governance policy information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company'],
                'indexes': [models.Index(fields=['domain'], name='companies_c_domain_99e280_idx'), models.Index(fields=['company'], name='companies_c_company_e71225_idx'), models.Index(fields=['carbon_neutral'], name='companies_c_carbon__84a82f_idx'), models.Index(fields=['parent'], name='companies_c_parent_7ceab3_idx')],
            },
        ),
    ]
