# Generated by Django 4.2.7 on 2025-09-18 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.PositiveIntegerField(default=1, help_text='Relevance score (1-10) - how similar the alternative is', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(blank=True, help_text='Optional description of why this is a good alternative', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_company', models.ForeignKey(help_text='The company that needs carbon neutral alternatives', on_delete=django.db.models.deletion.CASCADE, related_name='alternative_relationships', to='companies.company')),
                ('to_company', models.ForeignKey(help_text='The carbon neutral alternative company', on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for_relationships', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Alternative',
                'verbose_name_plural': 'Company Alternatives',
                'ordering': ['-relevance_score', 'to_company__company'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='carbon_neutral_alternatives',
            field=models.ManyToManyField(blank=True, help_text='Carbon neutral alternatives for this company', related_name='alternative_for', through='companies.CompanyAlternative', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='companyalternative',
            index=models.Index(fields=['from_company'], name='companies_c_from_co_7861a2_idx'),
        ),
        migrations.AddIndex(
            model_name='companyalternative',
            index=models.Index(fields=['to_company'], name='companies_c_to_comp_2bb117_idx'),
        ),
        migrations.AddIndex(
            model_name='companyalternative',
            index=models.Index(fields=['relevance_score'], name='companies_c_relevan_9c9964_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyalternative',
            unique_together={('from_company', 'to_company')},
        ),
    ]
