# Generated by Django 4.2.7 on 2025-09-22 05:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyalternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='origin',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of origin (ISO 3166-1 alpha-2 code)', max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['origin'], name='companies_c_origin_bb9b43_idx'),
        ),
    ]
