# Generated by Django 4.2.7 on 2025-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_origin_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='esg_policy',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.JSONField(blank=True, help_text="Description of the company in multiple languages (e.g., {'en': 'description', 'tr': 'açıklama'})", null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the company data is approved by an admin'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_approved'], name='companies_c_is_appr_380115_idx'),
        ),
    ]
