# Generated by Django 4.2.7 on 2025-10-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_esg_policy_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Primary domain of the company (e.g., google.com)', max_length=255, null=True, unique=True),
        ),
    ]
