# Generated by Django 4.2.7 on 2025-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_make_domain_optional'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='companies_c_domain_99e280_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.AddField(
            model_name='company',
            name='domains',
            field=models.JSONField(blank=True, default=list, help_text="List of domains owned by the company (e.g., ['google.com', 'alphabet.com'])"),
        ),
    ]
