# Generated by Django 4.2.7 on 2026-02-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_change_domain_to_domains_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='The domain that was searched but not found', max_length=255, unique=True)),
                ('request_count', models.PositiveIntegerField(default=1, help_text='Number of times this domain has been requested')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Optional notes from admin about this request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_requested_at', models.DateTimeField(auto_now_add=True, help_text='When this domain was last requested')),
                ('created_company', models.ForeignKey(blank=True, help_text='The company created from this request (if approved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_requests', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Request',
                'verbose_name_plural': 'Company Requests',
                'ordering': ['-request_count', '-last_requested_at'],
                'indexes': [models.Index(fields=['domain'], name='companies_c_domain_ce99eb_idx'), models.Index(fields=['status'], name='companies_c_status_77ba37_idx'), models.Index(fields=['request_count'], name='companies_c_request_3251fd_idx'), models.Index(fields=['-last_requested_at'], name='companies_c_last_re_6998c9_idx')],
            },
        ),
    ]
