# Generated by Django 4.2.7 on 2026-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_company_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_processed_date',
            field=models.DateField(blank=True, help_text='When the company data was processed/imported', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='data_updated_date',
            field=models.DateField(blank=True, help_text='When the company data was last updated in source', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='documents',
            field=models.JSONField(blank=True, default=list, help_text="List of certifications/documents (e.g., ['CE', 'ISO', 'ISO 22000'])"),
        ),
    ]
