version: '3.8'

services:
  nginx:
    build:
      context: ../../../../crewmeister-challenge/client
      dockerfile: ../Cache.Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    links:
      - server
    networks:
      - yesildoga
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.imdemo.rule=Host(`demo.im.dunklestoast.de`)'
      - 'traefik.http.routers.imdemo.tls=true'
      - 'traefik.http.routers.imdemo.tls.certresolver=lets-encrypt'
      - 'traefik.http.services.imdemo.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.imdemo.compress=true'
  server:
    build:
      context: ../../../../crewmeister-challenge/client
      dockerfile: ../Server.Dockerfile
    restart: unless-stopped
    networks:
      - yesildoga
    environment:
      SERVER_PORT: 1337
      SERVER_HOST: 0.0.0.0
      LOG_LEVEL: info
      NODE_ENV: production
  storybook:
    restart: unless-stopped
    build:
      context: ../../../../crewmeister-challenge/client
      dockerfile: ../Storybook.Dockerfile
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.imsb.rule=Host(`sb.im.dunklestoast.de`)'
      - 'traefik.http.routers.imsb.tls=true'
      - 'traefik.http.routers.imsb.tls.certresolver=lets-encrypt'
      - 'traefik.http.services.imsb.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.imsb.compress=true'

networks:
  yesildoga:
  web:
    external: true
